# Файл docker-compose.yml
#
# Перечень volume
# Файл docker-compose.yml
volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: eliasxio/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    image: eliasxio/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
# Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    image: eliasxio/taski_gateway
    volumes:
      - static:/staticfiles
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    ports:
      - 8000:80
    depends_on:
      - backend
    
